openapi: 3.0.0
info:
  version: 1.0.0
  title: Summary Care Record API
  description: |
    ## Overview
    ??

    ## Legal Use
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see ‘Onboarding’ below).

    ## Related APIs
    To use this API, you will need the patient's NHS number, which can be retrieved by using the following API:
      - [Personal Demographics Service (FHIR) API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) - use this API to search for patients and retrieve their details.  This API can also be used to update their details in some cases. This is the latest version of the PDS API and is recommended for all new integrators.

      When using this API, we also recommend that you consider using these related APIs:

      - [Female Genital Mutilation Information Sharing System (FGM-IS)](https://developer.nhs.uk/apis/fgm-v2.1/) - use this API to store and share FGM information of children under 18 with relevant NHS healthcare professionals across departments, organisations and geographical boundaries within England.

      - [Child Protection Information Sharing (CP-IS) - HL7 V3 API](https://digital.nhs.uk/services/child-protection-information-sharing-project/cp-is-domain-message-specification) - use this messaging and interactions guide to provide access to CP-IS, a sharing system which provides healthcare workers with access to recent unscheduled care attendance information for children under a local authority social care plan. 

      - [National Record Locator (NRL) (FHIR) API](https://developer.nhs.uk/apis/nrl/) - use this API to locate and share patient records held within local health and social care systems.

    ## API Status and Roadmap
    This API is in [alpha](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status) - expect further breaking changes.

    The API is currently available for sandbox testing, but not integration testing or for production use.

    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=all&tag=reasonable-adjustment-flag#controls).

    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis). 

    It also conforms to the [FHIR (STU3)](https://www.hl7.org/fhir/STU3/) global standard for health care data exchange.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules. In particular:
        - array names are singular, for example `line` not `lines` for address lines
        - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    ### Resources
    ??

    ## Network Access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network). To use this API with NHS smartcards (see below) you do need an HSCN connection, although internet-facing alternatives are available.

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).


    ## Authorisation
    This API is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present and authenticated to use it.

    The end user must be:
    - a healthcare professional
    - strongly authenticated, using either an NHS smartcard or a modern alternative available via [NHS Identity](https://digital.nhs.uk/services/nhs-identity)

    The API uses OAuth 2.0 to authorise the calling system. It supports the following security patterns:

    - [user-restricted RESTful API - using NHS Identity - combined authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-identity-combined-authentication-and-authorisation)
    - [user-restricted RESTful API - using NHS Identity - separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-identity-separate-authentication-and-authorisation)

    For more details, see [user-restricted APIs](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).


    ## Environments and testing
    | Purpose                                | Base URL                                            |
    | ---------------------------------------|-----------------------------------------------------|
    | Sandbox                                | `https://sandbox.service.nhs.uk/summary-care-record`|
    | Integration test                       | `https://int.service.nhs.uk/summary-care-record`    |



    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
      - is for early developer testing
      - only covers a limited set of scenarios
      - is stateless, so it does not actually persist any updates
      - is open access, so does not allow you to test authorisation

      For more details on sandbox testing, or to try out the sandbox using our \"Try this API\" feature, see the documentation for each endpoint.

    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.

  license:
    name: MIT
  contact:
    name: Summary Care Record FHIR API Support
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
x-nhsd-api-platform:
  meta:
    name: Summary Care Record API
    canonical_name: summary-care-record
    short_name: scr
    description: This is a generated template API
    pipeline_name_prefix: "Summary-Care-Record"
servers:
  - url: 'https://sandbox.api.service.nhs.uk/summary-care-record'
    description: Sandbox environment
tags:
  - name: SCR
paths:
  /Bundle:
    post:
      summary: Upload patient's Summary Care Record
      operationId: upload-scr
      tags:
        - SCR
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/Bundle.yaml
            example:
              $ref: components/examples/ScrUploadBundle.json
      responses:
        "201":
          description: SCR successfully uploaded
        "400":
          description: Bad request
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: invalid
                    details:
                      text: NHS number missing
        "403":
          description: No consent
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: forbidden
                    details:
                      text: There's no patient's consent to store SCR
        "500":
          description: Spine changed response structure
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: invalid
                    details:
                      text: Internal error
                      
  /DocumentReference:
    get:
      summary: Get patient's latest Summary Care Record identifier
      operationId: get-scr-id
      tags:
        - SCR
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
        - $ref: '#/components/parameters/RoleID'
        - in: query
          name: patient
          description: The patient's NHS Number. Must be preceded with FHIR identifier (eg."patient=https://fhir.nhs.uk/Id/nhs-number|9995000180")
          required: true
          example: https://fhir.nhs.uk/Id/nhs-number|9995000180
          schema:
            type: string
            
        - in: query
          name: type
          description: General Practice Summary snomed code. Must be equal "type=http://snomed.info/sct|196981000000101"
          required: false
          example: http://snomed.info/sct|196981000000101
          schema:
            type: string
          
        - in: query
          name: _sort
          description: Defines how Patient's SCR list should be sorted in order to retrieve the latest one. The only supported value is _sort=date. If a different value is provided HTTP 400 Bad Request will be returned.
          required: false
          example: date
          schema:
            type: string
             
        - in: query
          name: _count
          description: Defines the number of latest patient SCR IDs that sgould be retrieved. Currently the only supported value is _count=1. If a different value is provided HTTP 400 Bad Request will be returned.
          required: false
          example: 1
          schema:
            type: integer
              
      responses:
        "200":
          description: Success response
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/DocumentReferenceBundle.yaml
              example:
                $ref: components/examples/DocumentReferenceBundle.json

  /$setPermission:
    post:
      summary: Update patient's consent to View SCR
      operationId: acs
      tags:
        - SCR
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/CorrelationID'
        - $ref: '#/components/parameters/RequestID'
      requestBody:
        required: true
        content:
          application/fhir+json:
            schema:
              $ref: components/schemas/Parameters.yaml
            example:
              $ref: components/examples/SetPermission.json
      responses: 
        "200": 
          description: Success response
        "400":
          description: Bad request
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: invalid
                    details:
                      text: Invalid value - xyz in field 'valueCoding.code'

components:
  parameters:
    BearerAuthorization:
      in: header
      name: Authorization
      description: |
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis).
        Required in all environments except sandbox.
      required: false
      schema:
        type: string
        format: '^Bearer\ [[:ascii:]]+$'
        example: 'Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM'
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: |
        A globally unique identifier (GUID) for the request, which we use to trace the request if you contact our helpdesk.

        Mirrored back in a response header.

        Avoid `.` characters.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    RequestID:
      in: header
      name: X-Request-ID
      required: false
      description: |
        A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests.

        Must be a universally unique identifier (UUID) (ideally version 4).
        If you re-send a failed request, use the same value in this header.
        Mirrored back in a response header.
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068

    RoleID:
      in: header
      name: NHSD-Session-URID
      description: |

        The user role ID (URID) for the current session. Also known as a user role profile ID (URPID).

        For more details, see [determine the user’s role](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-identity-combined-authentication-and-authorisation#step-6-determine-the-user-s-role).

      required: false
      schema:
        type: string
        pattern: '^[0-9]+$'
        example: '555021935107'
